services:
  pingthings_db:
    image: postgres:15.1-alpine
    container_name: pingthings_db
    hostname: pingthings_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
        - pingthings_data_volume:/var/lib/postgresql
        - ./db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: 'homework'
      POSTGRES_USER: 'postgres'
    networks:
      - pingthings_network

  pingthings_db_ui:
    image: dpage/pgadmin4
    container_name: pingthings_db_ui
    hostname: pingthings_db_ui
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "valverde.thiago@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "p1n6th1n65"
    ports:
      - "80:80"
    volumes:
      - pingthings_data_ui_volume:/var/lib/pgadmin
    links:
      - pingthings_db
    networks:
      - pingthings_network

volumes:
  pingthings_data_volume:
    external: false
  pingthings_data_ui_volume:
    external: false

networks:
  pingthings_network:
    driver: bridge